//! Command-line and embedded runners for Schemalane migrations.
//!
//! The `schemalane` binary uses [`run_cli`]. Migration crates generated by
//! `schemalane init` use [`EmbeddedRunner`] so embedded Rust migration
//! executors and the normal CLI grammar share one dispatch path.

#![allow(clippy::print_stdout, clippy::print_stderr, clippy::future_not_send)]

mod args;
mod commands;
mod connect;
mod delegate;
mod dispatch;
mod observer;
mod prompt;
mod render;
mod runner;

pub use render::Verbosity;
pub use runner::{EmbeddedRunner, run_cli, run_cli_with};
