use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::{format_ident, quote};
use schemalane_version::ParsedVersion;
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use syn::{LitStr, parse_macro_input};

#[proc_macro]
/// Embeds Rust migrations and generates `migrations::{build_migrator, runner,
/// MIGRATIONS_DIR}`.
///
/// # Rebuild tracking
///
/// The directory is scanned during macro expansion. Adding or removing files
/// therefore needs an explicit Cargo dependency edge in the embedding crate:
///
/// ```text
/// fn main() {
///     println!("cargo::rerun-if-changed=migrations");
/// }
/// ```
///
/// Put this in `build.rs`. Crates generated by `schemalane init` include it.
pub fn embed_migrations(input: TokenStream) -> TokenStream {
    let relative_path = parse_macro_input!(input as LitStr);
    let relative_value = relative_path.value();

    let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(value) => value,
        Err(err) => {
            return compile_error(format!(
                "embed_migrations! could not resolve CARGO_MANIFEST_DIR: {err}"
            ));
        }
    };

    let manifest_dir = PathBuf::from(manifest_dir);
    let full_path = manifest_dir.join(&relative_value);
    if !full_path.exists() {
        return compile_error(format!(
            "embed_migrations! path does not exist: {}",
            full_path.display()
        ));
    }
    if !full_path.is_dir() {
        return compile_error(format!(
            "embed_migrations! path is not a directory: {}",
            full_path.display()
        ));
    }

    let canonical_path = match full_path.canonicalize() {
        Ok(path) => path,
        Err(err) => {
            return compile_error(format!(
                "embed_migrations! failed to canonicalize {}: {err}",
                full_path.display()
            ));
        }
    };

    let migrations = match discover_rust_migrations(&canonical_path) {
        Ok(migrations) => migrations,
        Err(err) => return compile_error(err),
    };

    let mut module_tokens = Vec::new();
    let mut registration_tokens = Vec::new();
    let mut used_idents = HashSet::new();

    for migration in migrations {
        let module_ident = unique_module_ident(&migration.script, &mut used_idents);
        let path_lit = lit_str_from_path(&migration.path);
        let script_lit = LitStr::new(&migration.script, Span::call_site());

        module_tokens.push(quote! {
            #[path = #path_lit]
            mod #module_ident;
        });

        registration_tokens.push(quote! {
            migrator.register_rust_migration(
                #script_lit,
                ::schemalane_core::RustMigrationExecutor::new(|client| {
                    Box::pin(#module_ident::migration(client))
                }),
            );
        });
    }

    let migrations_dir_lit = lit_str_from_path(&canonical_path);

    quote! {
        pub mod migrations {
            #(#module_tokens)*

            pub const MIGRATIONS_DIR: &str = #migrations_dir_lit;

            pub fn build_migrator(
                config: ::schemalane_core::SchemalaneConfig,
            ) -> ::schemalane_core::SchemalaneMigrator {
                let mut migrator = ::schemalane_core::SchemalaneMigrator::new(config);
                #(#registration_tokens)*
                migrator
            }

            pub fn runner() -> ::schemalane_cli::EmbeddedRunner {
                ::schemalane_cli::EmbeddedRunner::new(MIGRATIONS_DIR, build_migrator)
            }
        }
    }
    .into()
}

struct RustMigrationFile {
    path: PathBuf,
    script: String,
    version: ParsedVersion,
}

fn discover_rust_migrations(dir: &Path) -> Result<Vec<RustMigrationFile>, String> {
    let mut migrations = Vec::new();

    let read_dir = std::fs::read_dir(dir).map_err(|err| {
        format!(
            "failed to read migrations directory {}: {err}",
            dir.display()
        )
    })?;

    for entry in read_dir {
        let entry = entry
            .map_err(|err| format!("failed to read directory entry in {}: {err}", dir.display()))?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if !path
            .extension()
            .and_then(|ext| ext.to_str())
            .is_some_and(|ext| ext.eq_ignore_ascii_case("rs"))
        {
            continue;
        }

        let script = path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| format!("non-utf8 migration filename: {}", path.display()))?
            .to_owned();

        let version = parse_rust_migration_filename(&script)?;
        migrations.push(RustMigrationFile {
            path,
            script,
            version,
        });
    }

    migrations.sort_by(|a, b| {
        a.version
            .cmp(&b.version)
            .then_with(|| a.script.cmp(&b.script))
    });
    Ok(migrations)
}

fn parse_rust_migration_filename(
    file_name: &str,
) -> Result<schemalane_version::ParsedVersion, String> {
    schemalane_version::parse_rust_filename(file_name)
        .map(|(_, version, _)| version)
        .map_err(|error| error.to_string())
}

fn unique_module_ident(script: &str, used: &mut HashSet<String>) -> syn::Ident {
    let stem = script.strip_suffix(".rs").unwrap_or(script);
    let mut candidate = sanitize_ident(stem);
    let base = candidate.clone();
    let mut idx = 2usize;

    while !used.insert(candidate.clone()) {
        candidate = format!("{base}_{idx}");
        idx += 1;
    }

    format_ident!("{candidate}")
}

fn sanitize_ident(value: &str) -> String {
    let mut result = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push('_');
        }
    }

    result = result.trim_matches('_').to_owned();
    if result.is_empty() {
        result.push_str("migration");
    }
    if result
        .chars()
        .next()
        .is_some_and(|first| first.is_ascii_digit())
    {
        result = format!("m_{result}");
    }

    result
}

fn lit_str_from_path(path: &Path) -> LitStr {
    let as_string = path.to_string_lossy().into_owned();
    LitStr::new(&as_string, Span::call_site())
}

fn compile_error(message: impl AsRef<str>) -> TokenStream {
    let lit = LitStr::new(message.as_ref(), Span::call_site());
    quote! { compile_error!(#lit); }.into()
}

#[cfg(test)]
mod tests {
    use super::{parse_rust_migration_filename, sanitize_ident, unique_module_ident};
    use schemalane_version::ParsedVersion;

    fn parsed_version(parts: &[&str]) -> ParsedVersion {
        ParsedVersion::parse(&parts.join(".")).expect("fixture version")
    }

    #[test]
    fn parses_rust_migration_filename_with_dotted_description() {
        let version = parse_rust_migration_filename("V10__seed.reference_data.rs")
            .expect("dotted Rust migration description should parse");

        assert_eq!(version, parsed_version(&["10"]));
    }

    #[test]
    fn parses_rust_migration_filename_with_flyway_description() {
        let version = parse_rust_migration_filename("V001_002__My-description.data load.RS")
            .expect("Flyway-style Rust migration description should parse");

        assert_eq!(version, parsed_version(&["1", "2"]));
    }

    #[test]
    fn parses_uppercase_extension() {
        let version =
            parse_rust_migration_filename("V3__seed.RS").expect("uppercase .RS must parse");
        assert_eq!(version, parsed_version(&["3"]));
    }

    #[test]
    fn parses_rust_migration_filename_without_description() {
        let version =
            parse_rust_migration_filename("V1.rs").expect("description-less filename should parse");

        assert_eq!(version, parsed_version(&["1"]));
    }

    #[test]
    fn parses_large_rust_migration_version() {
        let version =
            parse_rust_migration_filename("V99999999999999999999999999999999999999__large.rs")
                .expect("large version should parse");

        assert_eq!(
            version,
            parsed_version(&["99999999999999999999999999999999999999"])
        );
    }

    #[test]
    fn sanitize_ident_edges() {
        assert_eq!(sanitize_ident("My-File.Name"), "my_file_name");
        assert_eq!(sanitize_ident("___"), "migration");
        assert_eq!(sanitize_ident("9lives"), "m_9lives");
        assert_eq!(sanitize_ident(""), "migration");
    }

    #[test]
    fn unique_module_ident_suffixes_collisions() {
        let mut used = std::collections::HashSet::new();
        let first = unique_module_ident("V9__m.rs", &mut used);
        let second = unique_module_ident("V9__m_.rs", &mut used);
        assert_eq!(first.to_string(), "v9__m");
        assert_eq!(second.to_string(), "v9__m_2");
    }
}
