/// Creates an embedded migration-crate scaffold at `path`.
pub fn init_migration_project(path: &Path, force: bool) -> Result<InitReport, SchemalaneError> {
    if path.exists() {
        if !path.is_dir() {
            return Err(SchemalaneError::Validation(format!(
                "init target exists and is not a directory: {}",
                path.display()
            )));
        }

        let has_entries = std::fs::read_dir(path)?.next().is_some();
        if has_entries && !force {
            return Err(SchemalaneError::Validation(format!(
                "init target directory is not empty: {} (use --force to overwrite)",
                path.display()
            )));
        }
    } else {
        std::fs::create_dir_all(path)?;
    }

    let package_name = sanitize_package_name(
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("migration"),
    );
    let lib_ident = package_to_lib_ident(&package_name);

    let files = init_template_files(&package_name, &lib_ident);
    let mut created = Vec::new();
    let mut overwritten = Vec::new();

    for (relative, content) in files {
        let target = path.join(relative);
        write_init_file(&target, &content, force, &mut created, &mut overwritten)?;
    }

    created.sort();
    overwritten.sort();

    Ok(InitReport {
        root: path.to_path_buf(),
        created,
        overwritten,
    })
}
fn write_init_file(
    path: &Path,
    content: &str,
    force: bool,
    created: &mut Vec<PathBuf>,
    overwritten: &mut Vec<PathBuf>,
) -> Result<(), SchemalaneError> {
    if path.exists() {
        if !force {
            return Err(SchemalaneError::Validation(format!(
                "refusing to overwrite existing file: {} (use --force to overwrite)",
                path.display()
            )));
        }
        overwritten.push(path.to_path_buf());
    } else {
        created.push(path.to_path_buf());
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

fn init_template_files(package_name: &str, lib_ident: &str) -> Vec<(PathBuf, String)> {
    vec![
        (
            PathBuf::from("Cargo.toml"),
            INIT_CARGO_TOML_TEMPLATE.replace("__PACKAGE_NAME__", package_name),
        ),
        (
            PathBuf::from("README.md"),
            INIT_PROJECT_README_TEMPLATE.to_owned(),
        ),
        (
            PathBuf::from(".gitignore"),
            INIT_GITIGNORE_TEMPLATE.to_owned(),
        ),
        (PathBuf::from("build.rs"), INIT_BUILD_RS_TEMPLATE.to_owned()),
        (
            PathBuf::from("src/main.rs"),
            INIT_MAIN_RS_TEMPLATE
                .replace("__PACKAGE_NAME__", package_name)
                .replace("__LIB_IDENT__", lib_ident),
        ),
        (PathBuf::from("src/lib.rs"), INIT_LIB_RS_TEMPLATE.to_owned()),
        (
            PathBuf::from("migrations/V1__create_cake_table.sql"),
            INIT_SQL_MIGRATION_TEMPLATE.to_owned(),
        ),
        (
            PathBuf::from("migrations/V2__seed_cake_table.rs"),
            INIT_RUST_MIGRATION_TEMPLATE.to_owned(),
        ),
    ]
}

fn sanitize_package_name(raw: &str) -> String {
    let mut package = String::new();
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
            package.push(ch.to_ascii_lowercase());
        } else {
            package.push('_');
        }
    }

    package = package.trim_matches(['-', '_']).to_owned();
    if package.is_empty() {
        package.push_str("migration");
    }

    if package
        .chars()
        .next()
        .is_some_and(|first| first.is_ascii_digit())
    {
        package = format!("m_{package}");
    }

    package
}

fn package_to_lib_ident(package_name: &str) -> String {
    package_name.replace('-', "_")
}

const INIT_CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "__PACKAGE_NAME__"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
schemalane-core = "0.1"
schemalane-cli = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7"

# Developing against a local schemalane checkout? Use path dependencies:
# schemalane-core = { path = "../schemalane-core" }
# schemalane-cli = { path = "../schemalane-cli" }
"#;

const INIT_PROJECT_README_TEMPLATE: &str = r#"# Migration Crate

Generated by `schemalane migrate init`.

This crate runs Schemalane migrations programmatically and exposes a small CLI:

- `up`
- `status`
- `fresh`

Rust migration registration is automatic via `embed_migrations!("./migrations")`.

Run from this crate:

```sh
DATABASE_URL="postgres://…" cargo run -- up
```

Run from parent project:

```sh
DATABASE_URL="postgres://…" cargo run --manifest-path ./migration/Cargo.toml -- up
```
"#;

const INIT_GITIGNORE_TEMPLATE: &str = "/target\n.env\n";

const INIT_BUILD_RS_TEMPLATE: &str = r#"fn main() {
    // Re-run when migrations are added or removed so embed_migrations! re-scans.
    println!("cargo::rerun-if-changed=migrations");
}
"#;

const INIT_MAIN_RS_TEMPLATE: &str = r"use __LIB_IDENT__::embedded;

#[tokio::main]
async fn main() {
    embedded::migrations::runner().run().await;
}
";

const INIT_LIB_RS_TEMPLATE: &str = r#"pub mod embedded {
    use schemalane_core::embed_migrations;

    embed_migrations!("./migrations");
}
"#;

const INIT_SQL_MIGRATION_TEMPLATE: &str = r"CREATE TABLE cake (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);
";

const INIT_RUST_MIGRATION_TEMPLATE: &str = r#"use tokio_postgres::Client;

pub async fn migration(client: &Client) -> Result<(), tokio_postgres::Error> {
    client
        .batch_execute(
            r"
INSERT INTO cake(name) VALUES ('vanilla');
INSERT INTO cake(name) VALUES ('chocolate');
",
        )
        .await?;
    Ok(())
}
"#;
use crate::{InitReport, SchemalaneError};
use std::path::{Path, PathBuf};
